name: geocat-tutorials
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - geocat-comp
  - geocat-viz
  - geocat-datafiles
  - uxarray
  - numpy
  - xarray
  - nc-time-axis
  - jupyterlab
  - jupyter_contrib_nbextensions
